training:
  #image channels
  num_channels : 3
  #TODO repalce batch size.
  batch_size : 1

  #model files
  model_path: 'model_files/'
  model_name: 'alexNet_model1370.meta'

  testeing_path: 'test_data'
  training_path: 'data/training_data'

  output_training_path: 'output/'


tensor_name:
  input_x: 'x'
  input_y_true: 'y_true'
  y_pred: 'y_pred'
  accuracy: 'accuracy'

visualizing:
  folder: ['visual']
  path: 'web/static/temp'

testing:
  folder: ['test']
  path_testing: 'data/test_data'
  path_using: 'web/static/temp'

